import Footer from '@/partials/footer/Footer';
import Header from '@/partials/header/Header';
import '@/styles/styles.scss';

export const metadata = {
  title: 'Dock App',
  description: 'Dock App Generated by M Irfan Ali',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <link rel='icon' type='image/x-icon' href='/assets/svgs/favicon.svg' />
      <body className='relative'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
